import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import theme from "@chakra-ui/theme";
import { ChakraProvider } from "@chakra-ui/react";
import { useEffect, useState } from "react";
import CountryList from "../components/CountryList";
import Country from "../components/Country";

export default function Home({ countries }) {
  const [stats, setStats] = useState([]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Hello World!</h2>
      <CountryList stats={countries} />
    </div>
  );
}

export async function getServerSideProps(ctx) {
  const countries = await fetch("https://api.covid19api.com/countries").then(
    (response) => response.json()
  );

  console.log(countries);

  return {
    props: {
      countries,
    },
  };
}
